stages:
  extract_jobs:
    cmd: python -m src.data.extract_jobs sqlite+pysqlite:///data/raw/job-server.db
      data/interim/jobs.csv
    deps:
    - data/raw/job-server.db
    - src/data/extract_jobs.py
    outs:
    - data/interim/jobs.csv
  transform_jobs:
    cmd: python -m src.data.transform_jobs data/interim/jobs.csv data/processed/jobs.feather
    deps:
    - data/interim/jobs.csv
    - src/data/transform_jobs.py
    outs:
    - data/processed/jobs.feather
  nbconvert:
    cmd: just run-jupyter nbconvert --execute --to=html --output-dir=reports notebooks/exploration.ipynb
    deps:
    - data/processed/jobs.feather
    - notebooks/exploration.ipynb
