[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories
    | \.direnv
    | \.github
    | \.pytest_cache
    | \.venv
    | htmlcov
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [".venv/*"]

[tool.coverage.report]
fail_under = 0
skip_covered = true

[tool.coverage.html]

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_glob = [".direnv", "venv", ".venv"]

[tool.pytest.ini_options]
